SELECT
    a.APPLICATION_MONTH,
    c.INDUSTRY,
    c.STATE,
    a.LOAN_PRODUCT,
    COUNT(*) AS TOTAL_APPLICATIONS,
    SUM(a.IS_APPROVED) AS TOTAL_APPROVALS,
    SUM(a.LOAN_AMOUNT) AS TOTAL_LOAN_AMOUNT,
    ROUND(AVG(a.LOAN_AMOUNT), 2) AS AVG_LOAN_AMOUNT,
    ROUND(AVG(a.CREDIT_SCORE), 0) AS AVG_CREDIT_SCORE,
    ROUND(AVG(a.DAYS_TO_DECISION), 1) AS AVG_DAYS_TO_DECISION,
    COUNT(DISTINCT a.CUSTOMER_ID) AS UNIQUE_CUSTOMERS,
    ROUND(SUM(a.IS_APPROVED) / COUNT(*) * 100, 1) AS APPROVAL_RATE
FROM {{ ref('silver_loan_applications') }} a
LEFT JOIN {{ ref('silver_customers') }} c
    ON a.CUSTOMER_ID = c.CUSTOMER_ID
GROUP BY a.APPLICATION_MONTH, c.INDUSTRY, c.STATE, a.LOAN_PRODUCT
ORDER BY a.APPLICATION_MONTH DESC, c.INDUSTRY
