WITH customer_loan_metrics AS (
    SELECT
        CUSTOMER_ID,
        COUNT(*) AS TOTAL_LOANS,
        SUM(LOAN_AMOUNT) AS TOTAL_EXPOSURE,
        SUM(TOTAL_REPAID) AS TOTAL_REPAID,
        AVG(CREDIT_SCORE) AS AVG_CREDIT_SCORE,
        AVG(PAYMENT_HEALTH_SCORE) AS AVG_PAYMENT_HEALTH,
        SUM(LATE_PAYMENT_COUNT) AS TOTAL_LATE_PAYMENTS,
        MAX(LAST_PAYMENT_DATE) AS LAST_ACTIVITY_DATE,
        AVG(INTEREST_RATE) AS AVG_INTEREST_RATE
    FROM {{ ref('gold_loan_performance') }}
    GROUP BY CUSTOMER_ID
)
SELECT
    c.CUSTOMER_ID,
    c.BUSINESS_NAME,
    c.INDUSTRY,
    c.STATE,
    c.ANNUAL_REVENUE,
    c.EMPLOYEES,
    c.YEARS_IN_BUSINESS,
    c.REVENUE_BAND,
    c.EMPLOYEE_BAND,
    COALESCE(m.TOTAL_LOANS, 0) AS TOTAL_LOANS,
    COALESCE(m.TOTAL_EXPOSURE, 0) AS TOTAL_EXPOSURE,
    COALESCE(m.TOTAL_REPAID, 0) AS TOTAL_REPAID,
    m.AVG_CREDIT_SCORE,
    m.AVG_PAYMENT_HEALTH,
    COALESCE(m.TOTAL_LATE_PAYMENTS, 0) AS TOTAL_LATE_PAYMENTS,
    m.LAST_ACTIVITY_DATE,
    m.AVG_INTEREST_RATE,
    CASE
        WHEN m.AVG_PAYMENT_HEALTH >= 80 THEN 'Low Risk'
        WHEN m.AVG_PAYMENT_HEALTH >= 50 THEN 'Medium Risk'
        WHEN m.AVG_PAYMENT_HEALTH IS NOT NULL THEN 'High Risk'
        ELSE 'No Loan History'
    END AS CUSTOMER_RISK_CATEGORY
FROM {{ ref('silver_customers') }} c
LEFT JOIN customer_loan_metrics m
    ON c.CUSTOMER_ID = m.CUSTOMER_ID
