WITH loan_txn_summary AS (
    SELECT
        LOAN_ID,
        SUM(CASE WHEN TRANSACTION_TYPE = 'Repayment' THEN AMOUNT ELSE 0 END) AS TOTAL_REPAID,
        SUM(CASE WHEN TRANSACTION_TYPE = 'Interest' THEN AMOUNT ELSE 0 END) AS TOTAL_INTEREST_PAID,
        SUM(CASE WHEN TRANSACTION_TYPE = 'Late Fee' THEN AMOUNT ELSE 0 END) AS TOTAL_LATE_FEES,
        COUNT(CASE WHEN TRANSACTION_TYPE = 'Late Fee' THEN 1 END) AS LATE_PAYMENT_COUNT,
        COUNT(CASE WHEN TRANSACTION_TYPE = 'Repayment' THEN 1 END) AS REPAYMENT_COUNT,
        MAX(TRANSACTION_DATE) AS LAST_PAYMENT_DATE
    FROM {{ ref('silver_transactions') }}
    GROUP BY LOAN_ID
)
SELECT
    a.APPLICATION_ID,
    a.CUSTOMER_ID,
    a.LOAN_PRODUCT,
    a.LOAN_AMOUNT,
    a.LOAN_TERM_MONTHS,
    a.INTEREST_RATE,
    a.RISK_TIER,
    a.CREDIT_SCORE,
    a.APPLICATION_DATE,
    a.DECISION_DATE,
    COALESCE(t.TOTAL_REPAID, 0) AS TOTAL_REPAID,
    COALESCE(t.TOTAL_INTEREST_PAID, 0) AS TOTAL_INTEREST_PAID,
    COALESCE(t.TOTAL_LATE_FEES, 0) AS TOTAL_LATE_FEES,
    COALESCE(t.LATE_PAYMENT_COUNT, 0) AS LATE_PAYMENT_COUNT,
    COALESCE(t.REPAYMENT_COUNT, 0) AS REPAYMENT_COUNT,
    t.LAST_PAYMENT_DATE,
    ROUND(COALESCE(t.TOTAL_REPAID, 0) / a.LOAN_AMOUNT * 100, 2) AS REPAYMENT_RATIO,
    GREATEST(0,
        100
        - (COALESCE(t.LATE_PAYMENT_COUNT, 0) * 10)
        - CASE WHEN COALESCE(t.TOTAL_REPAID, 0) / a.LOAN_AMOUNT * 100 < 20 THEN 20 ELSE 0 END
    ) AS PAYMENT_HEALTH_SCORE
FROM {{ ref('silver_loan_applications') }} a
LEFT JOIN loan_txn_summary t
    ON a.APPLICATION_ID = t.LOAN_ID
WHERE a.STATUS = 'Approved'
