WITH deduplicated AS (
    SELECT *,
        ROW_NUMBER() OVER (PARTITION BY CUSTOMER_ID ORDER BY CREATED_AT DESC) AS row_num
    FROM {{ source('raw', 'RAW_CUSTOMERS') }}
    WHERE ABN IS NOT NULL
      AND LENGTH(ABN) = 11
)
SELECT
    CUSTOMER_ID,
    BUSINESS_NAME,
    ABN,
    INDUSTRY,
    UPPER(TRIM(STATE)) AS STATE,
    ANNUAL_REVENUE,
    EMPLOYEES,
    YEARS_IN_BUSINESS,
    REGISTRATION_DATE,
    CREATED_AT,
    CASE
        WHEN ANNUAL_REVENUE < 500000 THEN 'Micro'
        WHEN ANNUAL_REVENUE < 2000000 THEN 'Small'
        WHEN ANNUAL_REVENUE < 10000000 THEN 'Medium'
        ELSE 'Large'
    END AS REVENUE_BAND,
    CASE
        WHEN EMPLOYEES < 5 THEN '1-4'
        WHEN EMPLOYEES < 20 THEN '5-19'
        WHEN EMPLOYEES < 100 THEN '20-99'
        ELSE '100+'
    END AS EMPLOYEE_BAND
FROM deduplicated
WHERE row_num = 1
