SELECT
    a.APPLICATION_ID,
    a.CUSTOMER_ID,
    a.APPLICATION_DATE,
    a.LOAN_AMOUNT,
    a.LOAN_PRODUCT,
    a.LOAN_TERM_MONTHS,
    a.INTEREST_RATE,
    a.PURPOSE,
    a.STATUS,
    a.DECISION_DATE,
    a.CREATED_AT,
    r.CREDIT_SCORE,
    r.RISK_TIER,
    r.DEBT_SERVICE_RATIO,
    r.COLLATERAL_VALUE,
    r.MODEL_VERSION,
    DATEDIFF('day', a.APPLICATION_DATE, a.DECISION_DATE) AS DAYS_TO_DECISION,
    DATE_TRUNC('month', a.APPLICATION_DATE) AS APPLICATION_MONTH,
    CASE WHEN a.STATUS = 'Approved' THEN 1 ELSE 0 END AS IS_APPROVED
FROM {{ source('raw', 'RAW_LOAN_APPLICATIONS') }} a
LEFT JOIN {{ source('raw', 'RAW_RISK_ASSESSMENTS') }} r
    ON a.APPLICATION_ID = r.APPLICATION_ID
WHERE a.STATUS != 'Withdrawn'
