SELECT
    TRANSACTION_ID,
    LOAN_ID,
    CUSTOMER_ID,
    TRANSACTION_DATE,
    AMOUNT,
    TRANSACTION_TYPE,
    STATUS,
    PAYMENT_METHOD,
    CREATED_AT,
    CASE WHEN TRANSACTION_TYPE = 'Late Fee' THEN TRUE ELSE FALSE END AS IS_LATE_PAYMENT,
    DATE_TRUNC('month', TRANSACTION_DATE) AS TRANSACTION_MONTH,
    CASE
        WHEN AMOUNT < 1000 THEN 'Small'
        WHEN AMOUNT < 10000 THEN 'Medium'
        WHEN AMOUNT < 100000 THEN 'Large'
        ELSE 'Very Large'
    END AS AMOUNT_CATEGORY
FROM {{ source('raw', 'RAW_TRANSACTIONS') }}
WHERE STATUS != 'Failed'
  AND AMOUNT > 0
